services:
    app.admin.user:
        class: Anton\WmsBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "WMS", label: "Пользователи" }
        arguments:
            - ~
            - Anton\WmsBundle\Entity\User
            - ~
    app.admin.product:
        class: Anton\WmsBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Продукты", label: "Товары" }
        arguments:
            - ~
            - Anton\WmsBundle\Entity\Product
            - ~
    app.admin.category:
        class: Anton\WmsBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Продукты", label: "Категории товаров" }
        arguments:
            - ~
            - Anton\WmsBundle\Entity\Category
            - ~
    app.admin.property:
        class: Anton\WmsBundle\Admin\PropertyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Продукты", label: "Свойства категорий товаров" }
        arguments:
            - ~
            - Anton\WmsBundle\Entity\Property
            - ~
    app.admin.property_values:
        class: Anton\WmsBundle\Admin\PropertyValuesAdmin
        tags:
            - { name: sonata.admin, show_in_dashboard: false, manager_type: orm, group: "Склады", label: "Значения свойств" }
        arguments:
            - ~
            - Anton\WmsBundle\Entity\ProductPropertyValue
            - ~
    app.admin.warehouse:
        class: Anton\WmsBundle\Admin\WarehouseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Склады", label: "Склады" }
        arguments:
            - ~
            - Anton\WmsBundle\Entity\Warehouse
            - ~
    app.admin.warehouse_category:
        class: Anton\WmsBundle\Admin\WarehouseCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Склады", label: "Категории складов" }
        arguments:
            - ~
            - Anton\WmsBundle\Entity\WarehouseCategory
            - ~
    app.admin.warehouse_property:
        class: Anton\WmsBundle\Admin\WarehousePropertyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Склады", label: "Свойства категорий складов" }
        arguments:
            - ~
            - Anton\WmsBundle\Entity\WarehouseProperty
            - ~
    app.admin.warehouse_property_values:
        class: Anton\WmsBundle\Admin\WarehousePropertyValuesAdmin
        tags:
            - { name: sonata.admin, show_in_dashboard: false, manager_type: orm, group: "Склады", label: "Значения свойств" }
        arguments:
            - ~
            - Anton\WmsBundle\Entity\WarehousePropertyValue
            - ~
    app.admin.map:
        class: Anton\WmsBundle\Admin\MapAdmin
        tags:
            - { name: sonata.admin, show_in_dashboard: false, manager_type: orm, group: "WMS", label: "Карта" }
        arguments:
            - ~
            - Anton\WmsBundle\Entity\Map
            - ~