product_detail:
  path: /product_detail/{id}
  defaults: { _controller: AntonWmsBundle:Ajax:ProductDetail }
  requirements:
       id: '\d+'

product_edit:
  path: /product_edit/{id}
  defaults: { _controller: AntonWmsBundle:Ajax:ProductEdit }
  requirements:
       id: '\d+'