product_receipt:
  path: /product-receipt/
  defaults: { _controller: AntonWmsBundle:Admin:productReceipt }

get_warehouses:
  path: /get-warehouses/{id}
  defaults: { _controller: AntonWmsBundle:Admin:getWarehouseByCategory }