services:
    wms.flush_handler:
        class: Anton\WmsBundle\EventHandler\UpdateHandler
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: onFlush }